### ISSUE TITLE
Needs option to pre-generate static validator file

### ISSUE THREAD

**Issue by jannone** [crodas/Validator#1]
I noticed the following line didn't actually generate code:
```
$val = new crodas\Validator\Init("src/", "src/Validator.php");
```
Instead, there is some runtime check going on where the lib looks for a cache, then generates the file on-the-fly.

It works; however, some production environments can't rely on PHP generated in runtime.

So I'd like to suggest this feature: a method to statically pre-generate everything, without cache file and without runtime checks.

Best Regards,
Rafael

**Comment by crodas** [comment]
@jannone fixed in the latest release (`0.2`). Let me know if there is anything else missing. I saw your point early this week and [I made it happen](https://github.com/crodas/Validator/blob/master/README.md#our-object)
